version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    tty: true
    volumes:
      - type: bind
        source: .
        target: /api
    ports:
      - '3000:3000'
    env_file:
      - .env.production.local
