import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  {
    id: 0,
    nameJa: '不明',
    nameEn: 'Unknown',
    slug: 'unknown',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 1,
    nameJa: 'アフリカ大陸',
    nameEn: 'Africa Continent',
    slug: 'africa-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 2,
    nameJa: 'アジア大陸',
    nameEn: 'Asia Continent',
    slug: 'asia-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 3,
    nameJa: 'オーストラリア大陸',
    nameEn: 'Australia Continent',
    slug: 'australia-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 4,
    nameJa: 'ヨーロッパ大陸',
    nameEn: 'Europe Continent',
    slug: 'europe-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 5,
    nameJa: '北アメリカ大陸',
    nameEn: 'North America Continent',
    slug: 'north-america-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 6,
    nameJa: '南アメリカ大陸',
    nameEn: 'South America Continent',
    slug: 'south-america-continent',
    parentId: null,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 7,
    nameJa: '北アフリカ',
    nameEn: 'North Africa',
    slug: 'north-africa',
    parentId: 1,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 8,
    nameJa: '西アフリカ',
    nameEn: 'West Africa',
    slug: 'west-africa',
    parentId: 1,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 9,
    nameJa: '中部アフリカ',
    nameEn: 'Central Africa',
    slug: 'central-africa',
    parentId: 1,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 10,
    nameJa: '東アフリカ',
    nameEn: 'East Africa',
    slug: 'east-africa',
    parentId: 1,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 11,
    nameJa: '南部アフリカ',
    nameEn: 'Southern Africa',
    slug: 'southern-africa',
    parentId: 1,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 12,
    nameJa: '中東',
    nameEn: 'Middle East',
    slug: 'middle-east',
    parentId: 2,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 13,
    nameJa: '東アジア',
    nameEn: 'East Asia',
    slug: 'east-asia',
    parentId: 2,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 14,
    nameJa: '東南アジア',
    nameEn: 'Southeast Asia',
    slug: 'southeast -asia',
    parentId: 2,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 15,
    nameJa: '南アジア',
    nameEn: 'South Asia',
    slug: 'south-asia',
    parentId: 2,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 16,
    nameJa: '中央アジア',
    nameEn: 'Central Asia',
    slug: 'central-asia',
    parentId: 2,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 17,
    nameJa: '西ヨーロッパ',
    nameEn: 'Western Europe',
    slug: 'west-europe',
    parentId: 4,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 18,
    nameJa: '中央ヨーロッパ',
    nameEn: 'Central Europe',
    slug: 'central-europe',
    parentId: 4,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 19,
    nameJa: '東ヨーロッパ',
    nameEn: 'Eastern Europe',
    slug: 'east-europe',
    parentId: 4,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 20,
    nameJa: '北ヨーロッパ',
    nameEn: 'Northern Europe',
    slug: 'north-europe',
    parentId: 4,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 21,
    nameJa: '南ヨーロッパ',
    nameEn: 'Southern Europe',
    slug: 'south-europe',
    parentId: 4,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 22,
    nameJa: '北部アメリカ',
    nameEn: 'North America',
    slug: 'north-america',
    parentId: 5,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 23,
    nameJa: '中央アメリカ',
    nameEn: 'Central America',
    slug: 'central-america',
    parentId: 5,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 24,
    nameJa: 'カリブ海地域',
    nameEn: 'Caribbean region',
    slug: 'caribbean',
    parentId: 5,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 25,
    nameJa: 'アンデス地域',
    nameEn: 'Andean region',
    slug: 'andean',
    parentId: 6,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 26,
    nameJa: 'ブラジル・プラタ地域',
    nameEn: 'Brazil-Plata region',
    slug: 'brazil-plata',
    parentId: 6,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 27,
    nameJa: 'アマゾン盆地地域',
    nameEn: 'Amazon basin region',
    slug: 'amazon',
    parentId: 6,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 28,
    nameJa: 'アフガニスタン',
    nameEn: 'Afghanistan',
    slug: 'afghanistan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 29,
    nameJa: 'アルバニア',
    nameEn: 'Albania',
    slug: 'albania',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 30,
    nameJa: 'アルジェリア',
    nameEn: 'Algeria',
    slug: 'algeria',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 31,
    nameJa: 'アンドラ',
    nameEn: 'Andorra',
    slug: 'andorra',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 32,
    nameJa: 'アンゴラ',
    nameEn: 'Angola',
    slug: 'angola',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 33,
    nameJa: 'アンチグア・バーブーダ',
    nameEn: 'Antigua and Barbuda',
    slug: 'antigua-barbuda',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 34,
    nameJa: 'アルゼンチン',
    nameEn: 'Argentina',
    slug: 'argentina',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 35,
    nameJa: 'アルメニア',
    nameEn: 'Armenia',
    slug: 'armenia',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 36,
    nameJa: 'オーストラリア',
    nameEn: 'Australia',
    slug: 'australia',
    parentId: 3,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 37,
    nameJa: 'オーストリア',
    nameEn: 'Austria',
    slug: 'austria',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 38,
    nameJa: 'アゼルバイジャン',
    nameEn: 'Azerbaijan',
    slug: 'azerbaijan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 39,
    nameJa: 'バハマ',
    nameEn: 'Bahamas',
    slug: 'bahamas',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 40,
    nameJa: 'バーレーン',
    nameEn: 'Bahrain',
    slug: 'bahrain',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 41,
    nameJa: 'バングラデシュ',
    nameEn: 'Bangladesh',
    slug: 'bangladesh',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 42,
    nameJa: 'バルバドス',
    nameEn: 'Barbados',
    slug: 'barbados',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 43,
    nameJa: 'ベラルーシ',
    nameEn: 'Belarus',
    slug: 'belarus',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 44,
    nameJa: 'ベルギー',
    nameEn: 'Belgium',
    slug: 'belgium',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 45,
    nameJa: 'ベリーズ',
    nameEn: 'Belize',
    slug: 'belize',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 46,
    nameJa: 'ベナン',
    nameEn: 'Benin',
    slug: 'benin',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 47,
    nameJa: 'ブータン',
    nameEn: 'Bhutan',
    slug: 'bhutan',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 48,
    nameJa: 'ボリビア',
    nameEn: 'Bolivia (Plurinational State of)',
    slug: 'bolivia',
    parentId: 25,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 49,
    nameJa: 'ボスニア・ヘルツェゴビナ',
    nameEn: 'Bosnia and Herzegovina',
    slug: 'bosnia-herzegovina',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 50,
    nameJa: 'ボツワナ',
    nameEn: 'Botswana',
    slug: 'botswana',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 51,
    nameJa: 'ブラジル',
    nameEn: 'Brazil',
    slug: 'brazil',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 52,
    nameJa: 'ブルネイ',
    nameEn: 'Brunei Darussalam',
    slug: 'brunei',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 53,
    nameJa: 'ブルガリア',
    nameEn: 'Bulgaria',
    slug: 'bulgaria',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 54,
    nameJa: 'ブルキナファソ',
    nameEn: 'Burkina Faso',
    slug: 'burkina',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 55,
    nameJa: 'ブルンジ',
    nameEn: 'Burundi',
    slug: 'burundi',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 56,
    nameJa: 'カーボベルデ',
    nameEn: 'Cabo Verde',
    slug: 'caboverde',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 57,
    nameJa: 'カンボジア',
    nameEn: 'Cambodia',
    slug: 'cambodia',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 58,
    nameJa: 'カメルーン',
    nameEn: 'Cameroon',
    slug: 'cameroon',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 59,
    nameJa: 'カナダ',
    nameEn: 'Canada',
    slug: 'canada',
    parentId: 22,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 60,
    nameJa: '中央アフリカ共和国',
    nameEn: 'Central African Republic',
    slug: 'car',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 61,
    nameJa: 'チャド',
    nameEn: 'Chad',
    slug: 'chad',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 62,
    nameJa: 'チリ',
    nameEn: 'Chile',
    slug: 'chile',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 63,
    nameJa: '中国',
    nameEn: 'China',
    slug: 'china',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 64,
    nameJa: 'コロンビア',
    nameEn: 'Colombia',
    slug: 'colombia',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 65,
    nameJa: 'コモロ',
    nameEn: 'Comoros',
    slug: 'comoros',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 66,
    nameJa: 'コンゴ',
    nameEn: 'Congo',
    slug: 'congo',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 67,
    nameJa: 'コスタリカ',
    nameEn: 'Costa Rica',
    slug: 'costarica',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 68,
    nameJa: 'コートジボアール',
    nameEn: "Cote D'Ivoire",
    slug: 'ivorycoast',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 69,
    nameJa: 'クロアチア',
    nameEn: 'Croatia',
    slug: 'croatia',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 70,
    nameJa: 'キューバ',
    nameEn: 'Cuba',
    slug: 'cuba',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 71,
    nameJa: 'キプロス',
    nameEn: 'Cyprus',
    slug: 'cyprus',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 72,
    nameJa: 'チェコ',
    nameEn: 'Czech Republic',
    slug: 'czechia',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 73,
    nameJa: '朝鮮民主主義人民共和国',
    nameEn: "Democratic People's Republic of Korea",
    slug: 'north-korea',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 74,
    nameJa: 'コンゴ民主共和国',
    nameEn: 'Democratic Republic of the Congo',
    slug: 'dr-congo',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 75,
    nameJa: 'デンマーク',
    nameEn: 'Denmark',
    slug: 'denmark',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 76,
    nameJa: 'ジブチ',
    nameEn: 'Djibouti',
    slug: 'djibouti',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 77,
    nameJa: 'ドミニカ',
    nameEn: 'Dominica',
    slug: 'dominica',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 78,
    nameJa: 'ドミニカ共和国',
    nameEn: 'Dominican Republic',
    slug: 'dominican-republic',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 79,
    nameJa: 'エクアドル',
    nameEn: 'Ecuador',
    slug: 'ecuador',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 80,
    nameJa: 'エジプト',
    nameEn: 'Egypt',
    slug: 'egypt',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 81,
    nameJa: 'エルサルバドル',
    nameEn: 'El Salvador',
    slug: 'elsalvador',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 82,
    nameJa: '赤道ギニア',
    nameEn: 'Equatorial Guinea',
    slug: 'equatorial-guinea',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 83,
    nameJa: 'エリトリア',
    nameEn: 'Eritrea',
    slug: 'eritrea',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 84,
    nameJa: 'エストニア',
    nameEn: 'Estonia',
    slug: 'estonia',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 85,
    nameJa: 'エスワティニ',
    nameEn: 'Eswatini',
    slug: 'eswatini',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 86,
    nameJa: 'エチオピア',
    nameEn: 'Ethiopia',
    slug: 'ethiopia',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 87,
    nameJa: 'フィジー',
    nameEn: 'Fiji',
    slug: 'fiji',
    parentId: 3,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 88,
    nameJa: 'フィンランド',
    nameEn: 'Finland',
    slug: 'finland',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 89,
    nameJa: 'フランス',
    nameEn: 'France',
    slug: 'france',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 90,
    nameJa: 'ガボン',
    nameEn: 'Gabon',
    slug: 'gabon',
    parentId: 9,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 91,
    nameJa: 'ガンビア',
    nameEn: 'Gambia (Republic of the)',
    slug: 'gambia',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 92,
    nameJa: 'ジョージア',
    nameEn: 'Georgia',
    slug: 'georgia',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 93,
    nameJa: 'ドイツ',
    nameEn: 'Germany',
    slug: 'germany',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 94,
    nameJa: 'ガーナ',
    nameEn: 'Ghana',
    slug: 'ghana',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 95,
    nameJa: 'ギリシャ',
    nameEn: 'Greece',
    slug: 'greece',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 96,
    nameJa: 'グレナダ',
    nameEn: 'Grenada',
    slug: 'grenada',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 97,
    nameJa: 'グアテマラ',
    nameEn: 'Guatemala',
    slug: 'guatemala',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 98,
    nameJa: 'ギニア',
    nameEn: 'Guinea',
    slug: 'guinea',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 99,
    nameJa: 'ギニアビサウ',
    nameEn: 'Guinea Bissau',
    slug: 'guineabissau',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 100,
    nameJa: 'ガイアナ',
    nameEn: 'Guyana',
    slug: 'guyana',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 101,
    nameJa: 'ハイチ',
    nameEn: 'Haiti',
    slug: 'haiti',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 102,
    nameJa: 'ホンジュラス',
    nameEn: 'Honduras',
    slug: 'honduras',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 103,
    nameJa: 'ハンガリー',
    nameEn: 'Hungary',
    slug: 'hungary',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 104,
    nameJa: 'アイスランド',
    nameEn: 'Iceland',
    slug: 'iceland',
    parentId: 20,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 105,
    nameJa: 'インド',
    nameEn: 'India',
    slug: 'india',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 106,
    nameJa: 'インドネシア',
    nameEn: 'Indonesia',
    slug: 'indonesia',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 107,
    nameJa: 'イラン（回教共和国）',
    nameEn: 'Iran(Islamic Republic of)',
    slug: 'iran',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 108,
    nameJa: 'イラク',
    nameEn: 'Iraq',
    slug: 'iraq',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 109,
    nameJa: 'アイルランド',
    nameEn: 'Ireland',
    slug: 'ireland',
    parentId: 20,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 110,
    nameJa: 'イスラエル',
    nameEn: 'Israel',
    slug: 'israel',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 111,
    nameJa: 'イタリア',
    nameEn: 'Italy',
    slug: 'italy',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 112,
    nameJa: 'ジャマイカ',
    nameEn: 'Jamaica',
    slug: 'jamaica',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 113,
    nameJa: '日本',
    nameEn: 'Japan',
    slug: 'japan',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 114,
    nameJa: 'ヨルダン',
    nameEn: 'Jordan',
    slug: 'jordan',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 115,
    nameJa: 'カザフスタン',
    nameEn: 'Kazakhstan',
    slug: 'kazakhstan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 116,
    nameJa: 'ケニア',
    nameEn: 'Kenya',
    slug: 'kenya',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 117,
    nameJa: 'キリバス',
    nameEn: 'Kiribati',
    slug: 'kiribati',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 118,
    nameJa: 'クウェート',
    nameEn: 'Kuwait',
    slug: 'kuwait',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 119,
    nameJa: 'キルギスタン',
    nameEn: 'Kyrgyzstan',
    slug: 'kyrgyzstan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 120,
    nameJa: 'ラオス人民民主共和国',
    nameEn: "Lao People's Democratic Republic",
    slug: 'laos',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 121,
    nameJa: 'ラトビア',
    nameEn: 'Latvia',
    slug: 'latvia',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 122,
    nameJa: 'レバノン',
    nameEn: 'Lebanon',
    slug: 'lebanon',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 123,
    nameJa: 'レソト',
    nameEn: 'Lesotho',
    slug: 'lesotho',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 124,
    nameJa: 'リベリア',
    nameEn: 'Liberia',
    slug: 'liberia',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 125,
    nameJa: 'リビア',
    nameEn: 'Libya',
    slug: 'libya',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 126,
    nameJa: 'リヒテンシュタイン',
    nameEn: 'Liechtenstein',
    slug: 'liechtenstein',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 127,
    nameJa: 'リトアニア',
    nameEn: 'Lithuania',
    slug: 'lithuania',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 128,
    nameJa: 'ルクセンブルク',
    nameEn: 'Luxembourg',
    slug: 'luxembourg',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 129,
    nameJa: 'マダガスカル',
    nameEn: 'Madagascar',
    slug: 'madagascar',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 130,
    nameJa: 'マラウィ',
    nameEn: 'Malawi',
    slug: 'malawi',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 131,
    nameJa: 'マレーシア',
    nameEn: 'Malaysia',
    slug: 'malaysia',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 132,
    nameJa: 'モルディブ',
    nameEn: 'Maldives',
    slug: 'maldives',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 133,
    nameJa: 'マリ',
    nameEn: 'Mali',
    slug: 'mali',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 134,
    nameJa: 'マルタ',
    nameEn: 'Malta',
    slug: 'malta',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 135,
    nameJa: 'マーシャル諸島',
    nameEn: 'Marshall Islands',
    slug: 'marshallis',
    parentId: 3,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 136,
    nameJa: 'モーリタニア',
    nameEn: 'Mauritania',
    slug: 'mauritania',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 137,
    nameJa: 'モーリシャス',
    nameEn: 'Mauritius',
    slug: 'mauritius',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 138,
    nameJa: 'メキシコ',
    nameEn: 'Mexico',
    slug: 'mexico',
    parentId: 22,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 139,
    nameJa: 'ミクロネシア連邦',
    nameEn: 'Micronesia(Federated States of)',
    slug: 'micronesia',
    parentId: 3,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 140,
    nameJa: 'モナコ',
    nameEn: 'Monaco',
    slug: 'monaco',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 141,
    nameJa: 'モンゴル',
    nameEn: 'Mongolia',
    slug: 'mongolia',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 142,
    nameJa: 'モンテネグロ',
    nameEn: 'Montenegro',
    slug: 'montenegro',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 143,
    nameJa: 'モロッコ',
    nameEn: 'Morocco',
    slug: 'morocco',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 144,
    nameJa: 'モザンビーク',
    nameEn: 'Mozambique',
    slug: 'mozambique',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 145,
    nameJa: 'ミャンマー',
    nameEn: 'Myanmar',
    slug: 'myanmar',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 146,
    nameJa: 'ナミビア',
    nameEn: 'Namibia',
    slug: 'namibia',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 147,
    nameJa: 'ナウル',
    nameEn: 'Nauru',
    slug: 'nauru',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 148,
    nameJa: 'ネパール',
    nameEn: 'Nepal',
    slug: 'nepal',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 149,
    nameJa: 'オランダ',
    nameEn: 'Netherlands',
    slug: 'netherlands',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 150,
    nameJa: 'ニュージーランド',
    nameEn: 'New Zealand',
    slug: 'new-zealand',
    parentId: 3,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 151,
    nameJa: 'ニカラグア',
    nameEn: 'Nicaragua',
    slug: 'nicaragua',
    parentId: 23,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 152,
    nameJa: 'ニジェール',
    nameEn: 'Niger',
    slug: 'niger',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 153,
    nameJa: 'ナイジェリア',
    nameEn: 'Nigeria',
    slug: 'nigeria',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 154,
    nameJa: '北マケドニア',
    nameEn: 'North Macedonia',
    slug: 'north-macedonia',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 155,
    nameJa: 'ノルウェー',
    nameEn: 'Norway',
    slug: 'norway',
    parentId: 20,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 156,
    nameJa: 'オマーン',
    nameEn: 'Oman',
    slug: 'oman',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 157,
    nameJa: 'パキスタン',
    nameEn: 'Pakistan',
    slug: 'pakistan',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 158,
    nameJa: 'パラオ',
    nameEn: 'Palau',
    slug: 'palau',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 159,
    nameJa: 'パナマ',
    nameEn: 'Panama',
    slug: 'panama',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 160,
    nameJa: 'パプア・ニューギニア',
    nameEn: 'Papua New Guinea',
    slug: 'papua-new-guinea',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 161,
    nameJa: 'パラグアイ',
    nameEn: 'Paraguay',
    slug: 'paraguay',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 162,
    nameJa: 'ペルー',
    nameEn: 'Peru',
    slug: 'peru',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 163,
    nameJa: 'フィリピン',
    nameEn: 'Philippines',
    slug: 'philippines',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 164,
    nameJa: 'ポーランド',
    nameEn: 'Poland',
    slug: 'poland',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 165,
    nameJa: 'ポルトガル',
    nameEn: 'Portugal',
    slug: 'portugal',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 166,
    nameJa: 'カタール',
    nameEn: 'Qatar',
    slug: 'qatar',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 167,
    nameJa: '韓国',
    nameEn: 'Republic of Korea',
    slug: 'korea',
    parentId: 13,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 168,
    nameJa: 'モルドバ',
    nameEn: 'Republic of Moldova',
    slug: 'moldova',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 169,
    nameJa: 'ルーマニア',
    nameEn: 'Romania',
    slug: 'romania',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 170,
    nameJa: 'ロシア',
    nameEn: 'Russian Federation',
    slug: 'russia',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 171,
    nameJa: 'ルワンダ',
    nameEn: 'Rwanda',
    slug: 'rwanda',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 172,
    nameJa: 'セントクリストファー・ネイビス',
    nameEn: 'Saint Kitts and Nevis',
    slug: 'saint-kitts',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 173,
    nameJa: 'セントルシア',
    nameEn: 'Saint Lucia',
    slug: 'saint-lucia',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 174,
    nameJa: 'セントビンセントおよびグレナディーン諸島',
    nameEn: 'Saint Vincent and the Grenadines',
    slug: 'saint-vincent',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 175,
    nameJa: 'サモア',
    nameEn: 'Samoa',
    slug: 'samoa',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 176,
    nameJa: 'サンマリノ',
    nameEn: 'San Marino',
    slug: 'sanmarino',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 177,
    nameJa: 'サントメ・プリンシペ',
    nameEn: 'Sao Tome and Principe',
    slug: 'saotome-principe',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 178,
    nameJa: 'サウジアラビア',
    nameEn: 'Saudi Arabia',
    slug: 'saudiarabia',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 179,
    nameJa: 'セネガル',
    nameEn: 'Senegal',
    slug: 'senegal',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 180,
    nameJa: 'セルビア',
    nameEn: 'Serbia',
    slug: 'serbia',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 181,
    nameJa: 'セイシェル',
    nameEn: 'Seychelles',
    slug: 'seychelles',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 182,
    nameJa: 'シエラレオネ',
    nameEn: 'Sierra Leone',
    slug: 'sierraleone',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 183,
    nameJa: 'シンガポール',
    nameEn: 'Singapore',
    slug: 'singapore',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 184,
    nameJa: 'スロバキア',
    nameEn: 'Slovakia',
    slug: 'slovakia',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 185,
    nameJa: 'スロベニア',
    nameEn: 'Slovenia',
    slug: 'slovenia',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 186,
    nameJa: 'ソロモン諸島',
    nameEn: 'Solomon Islands',
    slug: 'solomonis',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 187,
    nameJa: 'ソマリア',
    nameEn: 'Somalia',
    slug: 'somalia',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 188,
    nameJa: '南アフリカ',
    nameEn: 'South Africa',
    slug: 'south-africa',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 189,
    nameJa: '南スーダン',
    nameEn: 'South Sudan',
    slug: 'south-sudan',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 190,
    nameJa: 'スペイン',
    nameEn: 'Spain',
    slug: 'spain',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 191,
    nameJa: 'スリランカ',
    nameEn: 'Sri Lanka',
    slug: 'srilanka',
    parentId: 15,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 192,
    nameJa: 'スーダン',
    nameEn: 'Sudan',
    slug: 'sudan',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 193,
    nameJa: 'スリナム',
    nameEn: 'Suriname',
    slug: 'suriname',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 194,
    nameJa: 'スウェーデン',
    nameEn: 'Sweden',
    slug: 'sweden',
    parentId: 18,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 195,
    nameJa: 'スイス',
    nameEn: 'Switzerland',
    slug: 'switzerland',
    parentId: 17,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 196,
    nameJa: 'シリア',
    nameEn: 'Syrian Arab Republic',
    slug: 'syria',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 197,
    nameJa: 'タジキスタン',
    nameEn: 'Tajikistan',
    slug: 'tajikistan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 198,
    nameJa: 'タイ',
    nameEn: 'Thailand',
    slug: 'thailand',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 199,
    nameJa: '東ティモール',
    nameEn: 'Timor-Leste',
    slug: 'timor',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 200,
    nameJa: 'トーゴ',
    nameEn: 'Togo',
    slug: 'togo',
    parentId: 8,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 201,
    nameJa: 'トンガ',
    nameEn: 'Tonga',
    slug: 'tonga',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 202,
    nameJa: 'トリニダード・トバゴ',
    nameEn: 'Trinidad and Tobago',
    slug: 'trinidad-tobago',
    parentId: 24,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 203,
    nameJa: 'チュニジア',
    nameEn: 'Tunisia',
    slug: 'tunisia',
    parentId: 7,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 204,
    nameJa: 'トルコ',
    nameEn: 'Turkey',
    slug: 'turkey',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 205,
    nameJa: 'トルクメニスタン',
    nameEn: 'Turkmenistan',
    slug: 'turkmenistan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 206,
    nameJa: 'ツバル',
    nameEn: 'Tuvalu',
    slug: 'tuvalu',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 207,
    nameJa: 'ウガンダ',
    nameEn: 'Uganda',
    slug: 'uganda',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 208,
    nameJa: 'ウクライナ',
    nameEn: 'Ukraine',
    slug: 'ukraine',
    parentId: 19,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 209,
    nameJa: 'アラブ首長国連邦',
    nameEn: 'United Arab Emirates',
    slug: 'uae',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 210,
    nameJa: 'イギリス',
    nameEn: 'United Kingdom',
    slug: 'united-kingdom',
    parentId: 20,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 211,
    nameJa: 'タンザニア',
    nameEn: 'United Republic of Tanzania',
    slug: 'tanzania',
    parentId: 10,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 212,
    nameJa: 'アメリカ合衆国',
    nameEn: 'United States of America',
    slug: 'usa',
    parentId: 22,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 213,
    nameJa: 'ウルグアイ',
    nameEn: 'Uruguay',
    slug: 'uruguay',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 214,
    nameJa: 'ウズベキスタン',
    nameEn: 'Uzbekistan',
    slug: 'uzbekistan',
    parentId: 16,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 215,
    nameJa: 'バヌアツ',
    nameEn: 'Vanuatu',
    slug: 'vanuatu',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 216,
    nameJa: 'ベネズエラ',
    nameEn: 'Venezuela (Bolivarian Republic of)',
    slug: 'venezuela',
    parentId: 26,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 217,
    nameJa: 'ベトナム',
    nameEn: 'Viet Nam',
    slug: 'vietnam',
    parentId: 14,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 218,
    nameJa: 'イエメン',
    nameEn: 'Yemen',
    slug: 'yemen',
    parentId: 12,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 219,
    nameJa: 'ザンビア',
    nameEn: 'Zambia',
    slug: 'zambia',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
  {
    id: 220,
    nameJa: 'ジンバブエ',
    nameEn: 'Zimbabwe',
    slug: 'zimbabwe',
    parentId: 11,
    descriptionJa: null,
    descriptionEn: null,
  },
];

async function seedCountries() {
  for (const country of countries) {
    const newCountry = await prisma.country.create({
      data: country,
    });
    console.log(
      `Created new body: ${newCountry.nameEn} (ID: ${newCountry.id})`,
    );
  }
}

export default seedCountries;
