import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const federationCynologiqueInternationales = [
  {
    id: 1,
    nameEn: 'Gourp 1 - Sheepdogs and Cattledogs (except Swiss Cattledogs)',
    nameJa: 'Gourp 1 - Sheepdogs and Cattledogs (except Swiss Cattledogs)',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 2,
    nameEn:
      'Group 2 - Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',
    nameJa:
      'Group 2 - Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 3,
    nameEn: 'Group 3 - Terriers',
    nameJa: 'Group 3 - Terriers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 4,
    nameEn: 'Group 4 - Dachshunds',
    nameJa: 'Group 4 - Dachshunds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 5,
    nameEn: 'Group 5 - Spitz and primitive types',
    nameJa: 'Group 5 - Spitz and primitive types',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 6,
    nameEn: 'Group 6 - Scent hounds and related breeds',
    nameJa: 'Group 6 - Scent hounds and related breeds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 7,
    nameEn: 'Group 7 - Pointing Dogs',
    nameJa: 'Group 7 - Pointing Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 8,
    nameEn: 'Group 8 - Retrievers - Flushing Dogs - Water Dogs',
    nameJa: 'Group 8 - Retrievers - Flushing Dogs - Water Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 9,
    nameEn: 'Group 9 - Companion and Toy Dogs',
    nameJa: 'Group 9 - Companion and Toy Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 10,
    nameEn: 'Group 10 - Sighthounds',
    nameJa: 'Group 10 - Sighthounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: null,
  },
  {
    id: 11,
    nameEn: 'Section 1 : Sheepdogs',
    nameJa: 'Section 1 : Sheepdogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 1,
  },
  {
    id: 12,
    nameEn: 'Section 2 : Cattledogs (except Swiss Cattledogs)',
    nameJa: 'Section 2 : Cattledogs (except Swiss Cattledogs)',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 1,
  },
  {
    id: 13,
    nameEn: 'Section 1 : Pinscher and Schnauzer type',
    nameJa: 'Section 1 : Pinscher and Schnauzer type',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 2,
  },
  {
    id: 14,
    nameEn: 'Section 2 : Molossian type',
    nameJa: 'Section 2 : Molossian type',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 2,
  },
  {
    id: 15,
    nameEn: 'Section 3 : Swiss Mountain- and Cattledogs',
    nameJa: 'Section 3 : Swiss Mountain- and Cattledogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 2,
  },
  {
    id: 16,
    nameEn: 'Section 1 : Large and medium sized Terriers',
    nameJa: 'Section 1 : Large and medium sized Terriers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 3,
  },
  {
    id: 17,
    nameEn: 'Section 2 : Small sized Terriers',
    nameJa: 'Section 2 : Small sized Terriers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 3,
  },
  {
    id: 18,
    nameEn: 'Section 3 : Bull type Terriers',
    nameJa: 'Section 3 : Bull type Terriers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 3,
  },
  {
    id: 19,
    nameEn: 'Section 4 : Toy Terriers',
    nameJa: 'Section 4 : Toy Terriers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 3,
  },
  {
    id: 20,
    nameEn: 'Section 1 : Nordic Sledge Dogs',
    nameJa: 'Section 1 : Nordic Sledge Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 21,
    nameEn: 'Section 2 : Nordic Hunting Dogs',
    nameJa: 'Section 2 : Nordic Hunting Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 22,
    nameEn: 'Section 3 : Nordic Watchdogs and Herders',
    nameJa: 'Section 3 : Nordic Watchdogs and Herders',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 23,
    nameEn: 'Section 4 : European Spitz',
    nameJa: 'Section 4 : European Spitz',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 24,
    nameEn: 'Section 5 : Asian Spitz and related breeds',
    nameJa: 'Section 5 : Asian Spitz and related breeds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 25,
    nameEn: 'Section 6 : Primitive type',
    nameJa: 'Section 6 : Primitive type',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 26,
    nameEn: 'Section 7 : Primitive type - Hunting Dogs',
    nameJa: 'Section 7 : Primitive type - Hunting Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 5,
  },
  {
    id: 27,
    nameEn: 'Section 1 : Scent hounds',
    nameJa: 'Section 1 : Scent hounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 6,
  },
  {
    id: 28,
    nameEn: 'Section 2 : Leash (scent) Hounds',
    nameJa: 'Section 2 : Leash (scent) Hounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 6,
  },
  {
    id: 29,
    nameEn: 'Section 3 : Related breeds',
    nameJa: 'Section 3 : Related breeds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 6,
  },
  {
    id: 30,
    nameEn: 'Section 1 : Continental Pointing Dogs',
    nameJa: 'Section 1 : Continental Pointing Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 7,
  },
  {
    id: 31,
    nameEn: 'Section 2 : British and Irish Pointers and Setters',
    nameJa: 'Section 2 : British and Irish Pointers and Setters',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 7,
  },
  {
    id: 32,
    nameEn: 'Section 1 : Retrievers',
    nameJa: 'Section 1 : Retrievers',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 8,
  },
  {
    id: 33,
    nameEn: 'Section 2 : Flushing Dogs',
    nameJa: 'Section 2 : Flushing Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 8,
  },
  {
    id: 34,
    nameEn: 'Section 3 : Water Dogs',
    nameJa: 'Section 3 : Water Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 8,
  },
  {
    id: 35,
    nameEn: 'Section 1 : Bichons and related breeds',
    nameJa: 'Section 1 : Bichons and related breeds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 36,
    nameEn: 'Section 2 : Poodle',
    nameJa: 'Section 2 : Poodle',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 37,
    nameEn: 'Section 3 : Small Belgian Dogs',
    nameJa: 'Section 3 : Small Belgian Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 38,
    nameEn: 'Section 4 : Hairless Dogs',
    nameJa: 'Section 4 : Hairless Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 39,
    nameEn: 'Section 5 : Tibetan breeds',
    nameJa: 'Section 5 : Tibetan breeds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 40,
    nameEn: 'Section 6 : Chihuahueno',
    nameJa: 'Section 6 : Chihuahueno',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 41,
    nameEn: 'Section 7 : English Toy Spaniels',
    nameJa: 'Section 7 : English Toy Spaniels',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 42,
    nameEn: 'Section 8 : Japan Chin and Pekingese',
    nameJa: 'Section 8 : Japan Chin and Pekingese',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 43,
    nameEn: 'Section 9 : Continental Toy Spaniel and Russian Toy',
    nameJa: 'Section 9 : Continental Toy Spaniel and Russian Toy',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 44,
    nameEn: 'Section 10 : Kromfohrländer',
    nameJa: 'Section 10 : Kromfohrländer',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 45,
    nameEn: 'Section 11 : Small Molossian type Dogs',
    nameJa: 'Section 11 : Small Molossian type Dogs',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 9,
  },
  {
    id: 46,
    nameEn: 'Section 1 : Long-haired or fringed Sighthounds',
    nameJa: 'Section 1 : Long-haired or fringed Sighthounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 10,
  },
  {
    id: 47,
    nameEn: 'Section 2 : Rough-haired Sighthounds',
    nameJa: 'Section 2 : Rough-haired Sighthounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 10,
  },
  {
    id: 48,
    nameEn: 'Section 3 : Short-haired Sighthounds',
    nameJa: 'Section 3 : Short-haired Sighthounds',
    descriptionJa: null,
    descriptionEn: null,
    parentId: 10,
  },
];

async function seedFederationCynologiqueInternationales() {
  for (const federationCynologiqueInternationale of federationCynologiqueInternationales) {
    const newFederationCynologiqueInternationale =
      await prisma.federationCynologiqueInternationale.create({
        data: federationCynologiqueInternationale,
      });
    console.log(
      `Created new body: ${newFederationCynologiqueInternationale.nameEn} (ID: ${newFederationCynologiqueInternationale.id})`,
    );
  }
}

export default seedFederationCynologiqueInternationales;
