import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const roles = [
  {
    id: 0,
    nameEn: 'Unknown',
    nameJa: '不明',
    slug: 'unknown',
    descriptionEn: null,
    descriptionJa: null,
    parentId: null,
  },
  {
    id: 1,
    nameEn: 'Working dogs',
    nameJa: '使役犬',
    slug: 'work',
    descriptionEn: null,
    descriptionJa: null,
    parentId: null,
  },
  {
    id: 2,
    nameEn: 'Hunting dogs',
    nameJa: '猟犬',
    slug: 'hunt',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 1,
  },
  {
    id: 3,
    nameEn: 'Hounds',
    nameJa: 'ハウンド',
    slug: 'hound',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 4,
    nameEn: 'Sighthound',
    nameJa: '視覚ハウンド',
    slug: 'sight',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 3,
  },
  {
    id: 9,
    nameEn: 'Greyhound',
    nameJa: 'グレイハウンド',
    slug: 'grey',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 4,
  },
  {
    id: 10,
    nameEn: 'Scenthound',
    nameJa: '嗅覚ハウンド',
    slug: 'scent',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 3,
  },
  {
    id: 11,
    nameEn: 'Lurchers',
    nameJa: 'ラーチャー',
    slug: 'lurcher',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 5,
    nameEn: 'Gun dogs',
    nameJa: '狩猟犬',
    slug: 'gun',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 12,
    nameEn: 'Retrievers',
    nameJa: 'レトリバー（回収犬）',
    slug: 'retriever',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 5,
  },
  {
    id: 13,
    nameEn: 'Setters',
    nameJa: 'セッター',
    slug: 'setter',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 5,
  },
  {
    id: 14,
    nameEn: 'Spaniels',
    nameJa: 'スパニエル',
    slug: 'spaniel',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 5,
  },
  {
    id: 15,
    nameEn: 'Pointers',
    nameJa: 'ポインター',
    slug: 'pointer',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 5,
  },
  {
    id: 16,
    nameEn: 'Water dogs',
    nameJa: 'ウォーター・ドッグ',
    slug: 'water',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 5,
  },
  {
    id: 6,
    nameEn: 'Treeing dogs',
    nameJa: 'ツリーイング・ドッグ',
    slug: 'tree',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 17,
    nameEn: 'Feists',
    nameJa: 'フェイスト',
    slug: 'feist',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 6,
  },
  {
    id: 18,
    nameEn: 'Terriers',
    nameJa: 'テリア',
    slug: 'terrier',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 19,
    nameEn: 'Curs',
    nameJa: 'カー',
    slug: 'cur',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 20,
    nameEn: 'Dachshund',
    nameJa: 'ダックスフンド',
    slug: 'dachshund',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 2,
  },
  {
    id: 7,
    nameEn: 'Herding dogs',
    nameJa: '牧畜犬',
    slug: 'heeler',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 1,
  },
  {
    id: 21,
    nameEn: 'Sheep dogs',
    nameJa: '牧羊犬',
    slug: 'sheep',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 7,
  },
  {
    id: 22,
    nameEn: 'Cattle dogs',
    nameJa: '牧牛犬',
    slug: 'cattle',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 7,
  },
  {
    id: 23,
    nameEn: 'Sled dog',
    nameJa: 'そり犬',
    slug: 'sled',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 1,
  },
  {
    id: 8,
    nameEn: 'Fighting dog',
    nameJa: '闘犬',
    slug: 'fight',
    descriptionEn: null,
    descriptionJa: null,
    parentId: null,
  },
  {
    id: 24,
    nameEn: 'Mastiff',
    nameJa: 'マスティフ',
    slug: 'mastiff',
    descriptionEn: null,
    descriptionJa: null,
    parentId: 8,
  },
  {
    id: 25,
    nameEn: 'Other',
    nameJa: 'その他',
    slug: 'other',
    descriptionEn: null,
    descriptionJa: null,
    parentId: null,
  },
];

async function seedRoles() {
  for (const role of roles) {
    const newRole = await prisma.role.create({
      data: role,
    });
    console.log(`Created new body: ${newRole.nameEn} (ID: ${newRole.id})`);
  }
}

export default seedRoles;
