export const BREED_INCLUDE_FIELDS = {
  americanKennelClub: true,
  australianNationalKennelCouncil: true,
  body: true,
  canadianKennelClub: true,
  coat: true,
  colors: true,
  country: true,
  ear: true,
  eyes: true,
  federationCynologiqueInternationale: true,
  head: true,
  leg: true,
  newZealandKennelClub: true,
  patterns: true,
  role: true,
  size: true,
  status: true,
  tail: true,
  theKennelClub: true,
  unitedKennelClub: true,
};

export const COMMON_ENTITY_FIELD_MAP: Record<string, string> = {
  locale: 'locale',
  id: 'id',
  nameEn: 'nameEn',
  nameJa: 'nameJa',
  descriptionEn: 'descriptionEn',
  descriptionJa: 'descriptionJa',
};

export const BREED_ENTITY_FIELD_MAP: Record<string, string> = {
  id: 'id',
  nameEn: 'nameEn',
  nameJa: 'nameJa',
  descriptionEn: 'descriptionEn',
  descriptionJa: 'descriptionJa',
  kana: 'kana',
  minHeight: 'minHeight',
  maxHeight: 'maxHeight',
  minWeight: 'minWeight',
  maxWeight: 'maxWeight',
  americanKennelClub: 'americanKennelClub',
  australianNationalKennelCouncil: 'australianNationalKennelCouncil',
  colors: 'colors',
  colorConnection: 'colorConnection',
  eyes: 'eyes',
  eyeConnection: 'eyeConnection',
  patterns: 'patterns',
  patternConnection: 'patternConnection',
  canadianKennelClub: 'canadianKennelClub',
  coat: 'coat',
  country: 'country',
  ear: 'ear',
  federationCynologiqueInternationale: 'federationCynologiqueInternationale',
  leg: 'leg',
  newZealandKennelClub: 'newZealandKennelClub',
  role: 'role',
  size: 'size',
  status: 'status',
  tail: 'tail',
  theKennelClub: 'theKennelClub',
  unitedKennelClub: 'unitedKennelClub',
};
